### PR TITLE
Add option to block key press from being passed to target application

### PR DESCRIPTION
**Pull request by ipatalas**
Added an option to suppress key press. This is very handy if you want to do something upon the hot key but you don't want these keys to be sent to the target application.

Also made another small change to be compliant with `nCode` handling.

### CODE REVIEW

**Review by tuffstuff9 — APPROVED** [review]

**Comment by tuffstuff9** [comment]
Thanks for contributing @ipatalas!

**Comment by ipatalas** [comment]
BTW what's your release schedule more or less? For the time being I just have your repo referenced in my project directly so no pressure but ideally I'd rather end up with NuGet reference at some point.

**Comment by tuffstuff9** [comment]
> BTW what's your release schedule more or less? For the time being I just have your repo referenced in my project directly so no pressure but ideally I'd rather end up with NuGet reference at some point.

Sorry for the delay - totally forgot to update the nuget package. I've updated it now, please let me know if something is amiss.

**Comment by ipatalas** [comment]
No worries, just tried it and it works perfectly.

**Pull request merged**
